# Site wide configuration

title: www.brackmann.fr
description: "Avocat au barreau de Grasse"
logo: lawyer-logo-120x120.jpg
locale: fr_FR
url: //www.brackmann.fr
#url: //rbrackma.github.io/abc
#url: //10.64.109.18:4000

# meta data
tag : Avocat barreau de Grasse alentour Antibes Valbonne Mougins Biot Vallauris Sophia Antipolis Nice Cannes Nathalie Brackmann droit travail droit social droit famille PACA Cote d'Azur Lawyer

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist

# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Nathalie Brackmann
  web: http://www.brackmann.fr
  email: avocat@brackmann.fr
  avatar: brackmann-133x145.jpg
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
